image: continuumio/miniconda3:4.8.2

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - mkdir test-results
          - conda create -y -n test python=3.7
          - eval "$(conda shell.bash hook)" && conda activate test
          - pip install .[all]
          - conda install pandoc
          - cd docs
          - sphinx-build -M html source build
          - cd ..
          - python -m pytest tests/ --junitxml=test-results/nosetests.xml
          - black -l 120 --check .
