image: continuumio/miniconda3

pipelines:
  default:
    - step:
        script:
          - mkdir test-results
          - conda create -y -n test python=3.8
          - eval "$(conda shell.bash hook)" && conda activate test
          - pip install tox tox-conda
          - tox
