{% set setup_data = load_setup_py_data() %}

package:
  name: BioCantor
  version: {{ setup_data["version"] }}

source:
#  git_url: ../
  path: ../

build:
  noarch: generic
  number: "{{ GIT_DESCRIBE_NUMBER }}"
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python {{ python }}*
    {% for package in setup_data['install_requires'] %}
    - {{ package }}
    {% endfor %}

  run:
    - python {{ python }}*
    {% for package in setup_data['install_requires'] %}
    - {{ package }}
    {% endfor %}
